### ISSUE TITLE
4.1.2 and 4.1.3 break backwards compatibility

### ISSUE THREAD

**Issue by dchambers** [jquense/teaspoon#2]
Recently noticed that my Travis builds have started failing. On investigation this appears to be caused by the latest releases of teaspoon.

Whereas all the tests were working on 4.1.1, on 4.1.2 I get:

```
TypeError: $ is not a function
```

whereas on 4.1.3 I get:

```
TypeError: $(...).dom is not a function
```

Thanks again!

**Comment by jquense** [comment]
sorry, this one is tricky the first few versions are actually _broken_ they export the wrong file (ironically an old version of the lib), which is why I "fixed" it on a minor bump. But yeah if you were successfully using any of those versions its going to break you, which isn't something i counted one.

I'll unpublish and push the "fixed" version to 5.0

**Comment by jquense** [comment]
there ya go

**Comment by dchambers** [comment]
Lovely, thanks @jquense :+1:.

**Comment by dchambers** [comment]
Out of interest, what is the correct way to use teaspoon 5.0.0? The documentation still shows `$()` as being the main export:

```js
import $ from 'teaspoon';
```

which no longer appears to be the case.

**Comment by jquense** [comment]
The documentation is accurate for 5.0 the main export is still a jquery-esque function. The issue was that 4.0-4.1 was actually "broken" and exporting an old version of the library which followed the 3.x api, so essentially 4.0 was just 3.1.0...confusing I know

**Comment by dchambers** [comment]
Okay, finally got it, thanks!
